package com.jardo.usermodule.hbn;

import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.Date;

import org.dbunit.DatabaseUnitException;
import org.dbunit.dataset.DataSetException;
import org.dbunit.dataset.IDataSet;
import org.dbunit.dataset.ReplacementDataSet;
import org.dbunit.operation.DatabaseOperation;
import org.junit.Before;
import org.junit.Test;

import com.jardo.usermodule.containers.User;
import com.jardo.usermodule.containers.UserPassword;

public class UserDatabaseModelHbnTest extends UMDatabaseTestCase {

	private final UserDatabaseModelHbn databaseModel;

	public UserDatabaseModelHbnTest() {
		super();
		databaseModel = new UserDatabaseModelHbn(HibernateUtil.getSessionFactory());
	}

	@Override
	protected IDataSet createInitialDataSet() throws FileNotFoundException, DataSetException {
		ReplacementDataSet result = loadFlatXmlDataSet("src/test/resources/dataSets/userDatabaseModelHbnTest/initial.xml");

		result.addReplacementObject("[NOW]", new Date());

		return result;
	}

	@Override
	@Before
	protected void setUp() throws DatabaseUnitException, SQLException, Exception {
		DatabaseOperation.TRUNCATE_TABLE.execute(getConnection(), getDataSet());
		resetAutoGeneratedColumn("um_user", "id");
		DatabaseOperation.INSERT.execute(getConnection(), getDataSet());
	}

	@Test
	public void testAddPasswordResetToken() {
		fail("Not yet implemented");
	}

	@Test
	public void testAddUser() throws SQLException, Exception {
		UserPassword password = new UserPassword("ea1baa4cad9d822a51a1aa267a618fb2ac6d5d98a89709a595487ea493a69e90", "7886788cb39bf33c856ef18206a81ce4b498dc5a1a4199abc0cb0fb686eab008");
		User user = new User(-1, "carl", "carl@test.com", "ea587b759f423f0bfadfe7aeba0ee3fe", false, password);

		int result = databaseModel.addUser(user);

		assertEquals(4, result);

		IDataSet expectedDataSet = loadFlatXmlDataSet("src/test/resources/dataSets/userDatabaseModelHbnTest/afterAddUser.xml");

		assertTableContent(expectedDataSet, "um_user", new String[] { "reg_date", "rank" });
	}

	@Test
	public void testCancelAllPasswordResetTokens() {
		fail("Not yet implemented");
	}

	@Test
	public void testConfirmUserRegistration() {
		fail("Not yet implemented");
	}

	@Test
	public void testDeleteUser() {
		fail("Not yet implemented");
	}

	@Test
	public void testGetRegisteredUserCount() {
		fail("Not yet implemented");
	}

	@Test
	public void testGetNewestPasswordResetToken() {
		fail("Not yet implemented");
	}

	@Test
	public void testGetUserByEmail() {
		fail("Not yet implemented");
	}

	@Test
	public void testGetUserByName() {
		fail("Not yet implemented");
	}

	@Test
	public void testGetUserIdByEmail() {
		fail("Not yet implemented");
	}

	@Test
	public void testGetUserPassword() {
		fail("Not yet implemented");
	}

	@Test
	public void testIsEmailRegistered() {
		fail("Not yet implemented");
	}

	@Test
	public void testIsUserNameRegistered() {
		fail("Not yet implemented");
	}

	@Test
	public void testMakeLogInRecord() {
		fail("Not yet implemented");
	}

	@Test
	public void testSetUserPassword() {
		fail("Not yet implemented");
	}

}
